(() => {
 const records=window.JOJO_CHARACTERS||[], parts=window.JOJO_PARTS||[];
 const $=s=>document.querySelector(s); const search=$('#searchInput'), results=$('#searchResults'); let activePart=0,activeResult=-1,lastFocus=null,toastTimer;
 const partById=id=>parts.find(p=>p.id===id);
 const unknown=v=>v||'Kaynaklarda belirtilmemiş';
 function effectFor(c){if(c.id==='diavolo')return 'time-erasure';if(['dio-part3','jotaro-kujo'].includes(c.id))return 'time-stop';if(['dio-brando','kars','tooru'].includes(c.id))return 'eclipse';if(['jodio-joestar','meryl-mei-qi','charming-man'].includes(c.id))return 'lava';if(c.id==='yoshikage-kira')return 'detonation';if(c.id==='josuke-higashikata')return 'restoration';const s=norm([c.stand?.name,c.stand?.type,c.ability].join(' '));if(/rain|hava kontrol|weather/.test(s))return 'rain';if(/bubble|kabarc/.test(s))return 'bubbles';if(/tusk|spin|dönüş|mandom/.test(s))return 'spin';if(/gold experience|nesnelere yaşam/.test(s))return 'life';if(/hamon|ripple/.test(s))return 'ripple';if(/magician|flame|fire|alev/.test(s))return 'flame';if(/thread|string|ip temelli|zipper|fermuar|stone free/.test(s))return 'threads';if(/killer queen|bomba/.test(s))return 'detonation';if(/the hand/.test(s))return 'erase-space';if(/echoes|sound|ses efekt/.test(s))return 'sound';if(/sex pistols|mermi/.test(s))return 'bullet';if(/purple haze|virüs|poison/.test(s))return 'poison';if(/smooth operators|kaydır/.test(s))return 'shift';if(/the hustle|kas dok/.test(s))return 'muscle';if(/matte kudasai|isteğe dönüş/.test(s))return 'morph';if(/foo fighters|plankton/.test(s))return 'plankton';if(/gravity|whitesnake|pucci/.test(s))return 'gravity';if(/dinozor|scary monsters/.test(s))return 'dinosaur';if(/ghost|hayalet|burning down/.test(s))return 'haunted';if(/heaven|memory|bilgi ve kontrol/.test(s))return 'pages';if(/stand/.test(s))return 'stand';return 'fate'}
 const characterConnections={
  'jonathan-joestar':['Dio Brando — evlatlık kardeşi ve baş düşmanı','Erina Pendleton — hayat arkadaşı','Will A. Zeppeli — Hamon eğitmeni','Robert E. O. Speedwagon — sadık müttefik'],
  'dio-brando':['Jonathan Joestar — evlatlık kardeşi ve rakibi','George Joestar I — evlat edinen babası','Joestar ailesi — kuşaklar boyu süren düşmanlık'],
  'joseph-joestar':['Jonathan Joestar — büyükbabası','Lisa Lisa — annesi ve Hamon eğitmeni','Caesar Zeppeli — yol arkadaşı','Jotaro Kujo — torunu'],
  'jotaro-kujo':['Joseph Joestar — büyükbabası','Holly Kujo — annesi','Jolyne Cujoh — kızı','DIO — ailesinin baş düşmanı'],
  'josuke-higashikata':['Joseph Joestar — babası','Tomoko Higashikata — annesi','Okuyasu Nijimura ve Koichi Hirose — yakın dostları','Yoshikage Kira — Morioh’daki baş düşmanı'],
  'giorno-giovanna':['DIO — biyolojik babası','Jonathan Joestar — bedeninden gelen Joestar soy bağı','Bruno Bucciarati — ekip lideri ve müttefiki','Diavolo — Passione’deki düşmanı'],
  'jolyne-cujoh':['Jotaro Kujo — babası','Ermes Costello, Foo Fighters ve Emporio — hapishane müttefikleri','Enrico Pucci — baş düşmanı'],
  'johnny-joestar':['Gyro Zeppeli — yarış ortağı ve Spin eğitmeni','Lucy Steel — müttefik','Funny Valentine — baş düşmanı'],
  'josuke-gappy':['Yasuho Hirose — onu bulan ve soruşturmada destek olan müttefiki','Higashikata ailesi — geçmişinin araştırıldığı aile','Tooru — karşı karşıya geldiği düşman'],
  'jodio-joestar':['Dragona Joestar — kardeşi','Meryl Mei Qi — ekibin yöneticisi','Paco Lovelantes ve Usagi Alohaoe — ekip arkadaşları'],
  'dio-part3':['Jonathan Joestar — bedenini kullandığı düşmanı','Jotaro Kujo — son karşılaşmasındaki rakibi','Enrico Pucci — “Cennet” planını emanet ettiği müttefiki'],
  'caesar-zeppeli':['Joseph Joestar — önce rakibi, sonra yol arkadaşı','Lisa Lisa — Hamon eğitmeni','Zeppeli ailesi — Hamon geleneği'],
  'lisa-lisa':['Joseph Joestar — oğlu ve öğrencisi','Caesar Zeppeli — Hamon öğrencisi','Sütun Adamları — savaşta karşısındaki güç'],
  'mohammed-avdol':['Joseph Joestar — eski dostu','Jotaro Kujo’nun ekibi — Mısır yolculuğundaki müttefikleri','Iggy — zaman zaman çatıştığı ekip arkadaşı'],
  'noriaki-kakyoin':['Jotaro Kujo — onu DIO’nun kontrolünden kurtaran müttefiki','Muhammad Avdol ve Jean Pierre Polnareff — yol arkadaşları','DIO — geçmişteki düşmanı'],
  'jean-pierre-polnareff':['J. Geil — kız kardeşinin katili ve intikam hedefi','Jotaro Kujo’nun ekibi — Mısır yolculuğundaki müttefikleri','Bruno Bucciarati — Part 5’te yardım ettiği ekip lideri'],
  'koichi-hirose':['Josuke Higashikata — yakın arkadaşı','Yukako Yamagishi — ona ilgi duyan sınıf arkadaşı','Rohan Kishibe — karşılaştığı manga sanatçısı'],
  'okuyasu-nijimura':['Keicho Nijimura — ağabeyi','Josuke Higashikata — en yakın arkadaşı','Morioh grubu — Kira’ya karşı müttefikleri'],
  'rohan-kishibe':['Reimi Sugimoto — çocukluğundan tanıdığı hayalet','Koichi Hirose — sık sık birlikte çalıştığı genç','Josuke Higashikata — Morioh’daki çatışmaların müttefiki'],
  'yoshikage-kira':['Morioh sakinleri — kimliğini saklayarak aralarında yaşar','Kosaku Kawajiri — kimliğini gizlemek için kullandığı yaşam','Josuke Higashikata — onu durduran başlıca rakip'],
  'bruno-bucciarati':['Giorno Giovanna — ekibine aldığı müttefiki','Trish Una — koruma görevini üstlendiği kişi','Diavolo — Passione’nin gizli lideri ve düşmanı'],
  'meryl-mei-qi':['Jodio ve Dragona Joestar — görevlendirdiği kardeşler','Paco Lovelantes ve Usagi Alohaoe — ekip üyeleri','HOWLER şirketi — ekibin yeni hedefi'],
  'charming-man':['Mauka — kayboluşunu araştırdığı kardeşi','Jodio’nun ekibi — sonradan iş birliği yaptığı grup']
 };
 const norm=s=>(s||'').toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
 $('#characterCount').textContent=String(records.length).padStart(2,'0');
 function renderFilters(){const host=$('#partFilters');host.innerHTML='';[['ALL','TÜM PART’LAR',0],...parts.map(p=>[String(p.id).padStart(2,'0'),p.label,p.id])].forEach(([num,label,id])=>{const b=document.createElement('button');b.type='button';b.className='part-filter'+(id===activePart?' active':'');b.textContent=id===0?'TÜM PART’LAR':`${num} · ${label}`;b.setAttribute('aria-pressed',id===activePart);b.onclick=()=>{activePart=id;renderFilters();renderCards()};host.append(b)})}
 function renderCards(){const host=$('#characterGrid'),filtered=activePart?records.filter(c=>c.part===activePart):records;host.innerHTML='';$('#emptyState').hidden=filtered.length>0;filtered.forEach((c,i)=>{const card=document.createElement('article');card.className='character-card';card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label',`${c.name}, Part ${c.part}${c.stand?`, Stand ${c.stand.name}`:''}`);card.innerHTML=`<span class="card-index">${String(i+1).padStart(2,'0')}</span><span class="card-part">PART ${String(c.part).padStart(2,'0')}</span><h3>${esc(c.name)}</h3><span class="card-role">${esc(c.role)}</span>${c.stand?`<span class="card-stand"><span>STAND / </span>${esc(c.stand.name)}</span>`:''}`;card.onclick=()=>openProfile(c);card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openProfile(c)}};host.append(card)})}
 function esc(s){return String(s||'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
 function showResults(){const q=norm(search.value.trim());results.innerHTML='';activeResult=-1;if(!q){results.classList.remove('open');search.setAttribute('aria-expanded','false');return}const found=[];for(const c of records){const name=norm(c.name),stand=norm(c.stand?.name);if(name.includes(q)||stand.includes(q))found.push({c,matchedStand:!name.includes(q)&&stand.includes(q)});if(found.length===8)break}if(!found.length){const empty=document.createElement('div');empty.className='search-result';empty.textContent='Sonuç bulunamadı';results.append(empty)}else for(const {c,matchedStand} of found){const b=document.createElement('button');b.type='button';b.className='search-result';b.setAttribute('role','option');b.innerHTML=`<span><strong>${esc(c.name)}</strong><small>${matchedStand?'Stand: '+esc(c.stand.name):esc(c.role)}</small></span><span class="result-part">PART ${String(c.part).padStart(2,'0')} ↗</span>`;b.addEventListener('mousedown',e=>e.preventDefault());b.onclick=()=>{results.classList.remove('open');search.setAttribute('aria-expanded','false');search.value='';openProfile(c,matchedStand)};results.append(b)}results.classList.add('open');search.setAttribute('aria-expanded','true')}
 search.addEventListener('input',showResults);$('#searchForm').addEventListener('submit',e=>{e.preventDefault();const q=norm(search.value.trim());const c=records.find(x=>norm(x.name)===q||norm(x.stand?.name)===q)||records.find(x=>norm(x.name).includes(q)||norm(x.stand?.name).includes(q));if(c){openProfile(c,norm(c.stand?.name)===q);search.value='';results.classList.remove('open');search.setAttribute('aria-expanded','false')}else showResults()});document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap')){results.classList.remove('open');search.setAttribute('aria-expanded','false')}});
 search.addEventListener('keydown',e=>{const opts=[...results.querySelectorAll('button')];if(e.key==='ArrowDown'&&opts.length){e.preventDefault();activeResult=(activeResult+1)%opts.length;updateActive(opts)}if(e.key==='ArrowUp'&&opts.length){e.preventDefault();activeResult=(activeResult-1+opts.length)%opts.length;updateActive(opts)}if(e.key==='Escape'){results.classList.remove('open');search.setAttribute('aria-expanded','false')}if(e.key==='Enter'&&activeResult>=0){e.preventDefault();opts[activeResult].click()}});function updateActive(opts){opts.forEach((o,i)=>o.classList.toggle('active',i===activeResult));opts[activeResult]?.scrollIntoView({block:'nearest'})}
 function openProfile(c,openStand=false){lastFocus=document.activeElement;const overlay=$('#profileOverlay'),part=partById(c.part),profilePanel=$('#profilePanel');profilePanel.dataset.effect=effectFor(c);profilePanel.querySelector('.profile-effects').dataset.label=c.stand?.name||c.name;$('#profileName').textContent=c.name;$('#profilePartLabel').textContent=`PART ${String(c.part).padStart(2,'0')} · ${part?.label||''}`;$('#profileEyebrow').textContent=c.role.toUpperCase();$('#profileAlias').textContent=c.alias||'';$('#profileIntro').textContent=c.intro;const characterDetail=window.JOJO_CHARACTER_DETAILS?.[c.id];$('#characterDetailSection').hidden=!characterDetail;$('#characterDetail').textContent=characterDetail||'';$('#factsGrid').innerHTML='';[['DOĞUM','birth'],['BOY','height'],['KİŞİLİK','personality'],['YETENEK','ability']].forEach(([label,key])=>{const item=document.createElement('div');item.className='fact';item.innerHTML=`<span class="fact-label">${label}</span><span class="fact-value">${esc(unknown(c[key]))}</span>`;$('#factsGrid').append(item)});$('#eventList').innerHTML='';(c.events||[]).forEach(text=>{const li=document.createElement('li');li.textContent=text;$('#eventList').append(li)});const ties=characterConnections[c.id]||[];$('#connectionsSection').hidden=!ties.length;$('#connectionList').innerHTML='';ties.forEach(text=>{const li=document.createElement('li');li.textContent=text;$('#connectionList').append(li)});const partUrls={1:'pb',2:'bt',3:'sc',4:'du',5:'gw',6:'so',7:'sbr',8:'jl',9:'tjl'};const source=$('#profileSource');source.textContent=(c.source||'Manga/anime canon’u.')+' ';const sourceLink=document.createElement('a');sourceLink.href=`https://jojo-portal.com/en/about/${partUrls[c.part]}/`;sourceLink.target='_blank';sourceLink.rel='noreferrer';sourceLink.textContent='Resmî JoJo portalı · Part '+c.part;source.append(sourceLink);
 const img=$('#characterImage'),art=$('#characterArt'),aside=$('#profileAside');img.hidden=true;art.hidden=true;aside.hidden=!c.stand;$('#standCard').hidden=!c.stand;$('#standEmpty').hidden=true;if(c.stand)$('#standCardName').textContent=c.stand.name;const thumb=$('#standThumb');thumb.hidden=true;$('#standCard').dataset.hasImage='false';if(c.stand?.image){thumb.onload=()=>{thumb.hidden=false;$('#standCard').dataset.hasImage='true'};thumb.onerror=()=>{thumb.hidden=true};thumb.alt=c.stand.name+' görseli';thumb.src=c.stand.image}overlay.hidden=false;document.body.classList.add('modal-open');$('#closeProfile').focus();if(openStand&&c.stand)setTimeout(()=>openStandPanel(c),80)}
 function closeProfile(){if(!$('#standOverlay').hidden)return;$('#profileOverlay').hidden=true;document.body.classList.remove('modal-open');lastFocus?.focus?.()}
 function openStandPanel(c){if(!c.stand)return;const panel=$('#standPanel');panel.dataset.effect=effectFor(c);$('#standVisual').dataset.label=c.stand.name;$('#standArtworkLabel').textContent=c.stand.name;$('#standOwner').textContent=`KULLANICI / ${c.name.toUpperCase()}`;$('#standTitle').textContent=c.stand.name;$('#standType').textContent=c.stand.type||'Stand türü kaynaklarda belirtilmemiş';$('#standDescription').textContent=c.stand.description||'Stand hakkında ayrıntı kaynaklarda belirtilmemiş.';$('#standFacts').innerHTML='';Object.entries(c.stand.facts||{}).forEach(([k,v])=>{const row=document.createElement('div');row.className='stand-fact';row.innerHTML=`<span>${esc(k.toUpperCase())}</span><span>${esc(v)}</span>`;$('#standFacts').append(row)});if(!c.stand.facts||!Object.keys(c.stand.facts).length){const row=document.createElement('div');row.className='stand-fact';row.innerHTML='<span>AYRINTI</span><span>Kaynaklarda belirtilmemiş</span>';$('#standFacts').append(row)}const extras=window.JOJO_STAND_DETAILS?.[c.id]||{},fillList=(id,section,items)=>{const target=$(id);target.innerHTML='';(items||[]).forEach(text=>{const li=document.createElement('li');li.textContent=text;target.append(li)});$(section).hidden=!(items||[]).length};fillList('#standDetails','#standDetailsSection',c.stand.details||extras.details);fillList('#standLimits','#standLimitsSection',c.stand.limits||extras.limits);const frame=$('#standImageFrame'),picture=$('#standImage');frame.hidden=true;picture.hidden=true;picture.onload=()=>{picture.hidden=false;frame.hidden=false};picture.onerror=()=>{picture.hidden=true;frame.hidden=true};if(c.stand.image){picture.src=c.stand.image;picture.alt=c.stand.name+' görseli'}$('#standOverlay').hidden=false;$('#closeStand').focus()}
 function closeStand(){if($('#standOverlay').hidden)return;$('#standOverlay').hidden=true;$('#standCard').focus()}
 $('#standCard').onclick=()=>{const name=$('#profileName').textContent;const c=records.find(x=>x.name===name);openStandPanel(c)};$('#closeProfile').onclick=closeProfile;$('#closeStand').onclick=closeStand;$('#profileOverlay').addEventListener('click',e=>{if(e.target===$('#profileOverlay'))closeProfile()});$('#standOverlay').addEventListener('click',e=>{if(e.target===$('#standOverlay'))closeStand()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#standOverlay').hidden)closeStand();else if(!$('#profileOverlay').hidden)closeProfile()}if(e.key==='/'&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)&&$('#profileOverlay').hidden){e.preventDefault();search.focus()}});
 $('#aboutButton').onclick=()=>$('#aboutDialog').showModal();$('#closeAbout').onclick=()=>$('#aboutDialog').close();$('#aboutOk').onclick=()=>$('#aboutDialog').close();$('#aboutDialog').addEventListener('click',e=>{if(e.target===$('#aboutDialog'))$('#aboutDialog').close()});
 function heroPortraits(){const host=$('#heroArt');const heroIds=['jonathan-joestar','joseph-joestar','jotaro-kujo','josuke-higashikata','giorno-giovanna','jolyne-cujoh','johnny-joestar','josuke-gappy'];heroIds.forEach((id,i)=>{const c=records.find(entry=>entry.id===id);if(!c)return;const src=`assets/characters/${id}.webp`,im=new Image();im.onload=()=>{const figure=document.createElement('img');figure.className='hero-portrait '+(i%2===0?'from-bottom':'from-top');figure.src=src;figure.alt='';figure.style.setProperty('--portrait-index',i);figure.style.left=`${1+i*12.15}%`;figure.style.animationDelay=`${i*90}ms`;host.append(figure)};im.onerror=()=>{};im.src=src})}
 renderFilters();renderCards();heroPortraits();
})();








