/* Canon character records. Add or update entries here; the interface is generated from this file. Unknown fields should stay explicitly unknown. */
window.JOJO_CHARACTERS = [
 {id:'jonathan-joestar',name:'Jonathan Joestar',part:1,role:'JoJo · Phantom Blood',intro:'Joestar ailesinin ilk JoJo’su. Centilmenlik ve kararlılığıyla Dio Brando’ya karşı durur.',birth:'4 Nisan 1868',height:'195 cm',personality:'Nazik, cesur ve onurlu',ability:'Hamon (Ripple)',stand:null,events:['Dio Brando’nun Joestar ailesine katılmasıyla başlayan düşmanlığın merkezinde yer alır.','Will A. Zeppeli’den Hamon öğrenir ve Dio’nun vampir güçlerine karşı savaşır.','Dio’yu durdurmak için hayatını feda eder; soyunun devamı Erina ile sürer.'],image:null,source:'Manga: Phantom Blood (Part 1); resmî anime portalı.'},
 {id:'dio-brando',name:'Dio Brando',part:1,role:'Baş düşman · Phantom Blood',intro:'Joestar ailesine evlatlık olarak katılan Dio, güç ve ölümsüzlük arzusuyla Jonathan’ın baş düşmanına dönüşür.',birth:'12 Nisan 1867',height:'Kaynaklarda belirtilmemiş',personality:'Hırslı, acımasız ve manipülatif',ability:'Taş Maske; vampir yetenekleri',stand:null,standInfo:null,events:['George Joestar’ın evine evlatlık gelir ve Jonathan’la rekabete girer.','Taş Maske’yi kullanarak vampire dönüşür.','Jonathan’la çatışması denizdeki son mücadeleye taşınır.'],image:null,source:'Manga: Phantom Blood (Part 1); resmî anime portalı.'},
 {id:'joseph-joestar',name:'Joseph Joestar',part:2,role:'JoJo · Battle Tendency',intro:'Jonathan’ın torunu Joseph, kurnazlığı ve doğaçlamasıyla Sütun Adamları’na karşı mücadele eder.',birth:'27 Eylül 1920',height:'195 cm',personality:'Şakacı, kurnaz ve cesur',ability:'Hamon (Part 2); Hermit Purple Stand (Part 3)',stand:{name:'Hermit Purple',image:'assets/stands/hermit-purple.webp',type:'Dikenli sarmaşık biçimli Stand',description:'Joseph’in Hamon’la kullanabildiği sarmaşık biçimli Stand; uzaktan algılama ve spiritüel fotoğrafçılık amacıyla kullanır.',facts:{'Yetenek':'Sarmaşık saldırıları ve spiritüel görüntüleme','Kullanıcı':'Joseph Joestar','İlk görüldüğü Part':'Part 3'}},events:['Speedwagon Vakfı ve Caesar Zeppeli ile Sütun Adamları’nı araştırır.','Lisa Lisa’nın eğitimiyle Hamon becerisini geliştirir.','Kars’ı uzaya savurup Dünya için tehdidini sona erdirir.'],image:null,source:'Manga: Battle Tendency (Part 2) ve Stardust Crusaders (Part 3).'},
 {id:'caesar-zeppeli',name:'caesar-zeppeli',name:'Caesar Anthonio Zeppeli',part:2,role:'Hamon kullanıcısı · Battle Tendency',intro:'Zeppeli ailesinin Hamon kullanıcısı ve Joseph’in yol arkadaşı.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Gururlu, tutkulu ve sadık',ability:'Hamon; sabun köpüğü tekniği',stand:null,events:['Joseph’le önce rekabet eder, sonra Sütun Adamları’na karşı birlikte savaşır.','Wamuu ile çarpışmasında hayatını kaybeder ve Hamon’unu Joseph’e aktarır.'],image:null,source:'Manga: Battle Tendency (Part 2).'},
 {id:'jotaro-kujo',name:'Jotaro Kujo',part:3,role:'JoJo · Stardust Crusaders',intro:'DIO’nun yeniden ortaya çıkışı üzerine Mısır’a uzanan yolculuğa çıkan, soğukkanlı bir Joestar.',birth:'1970 (doğum günü belirtilmemiş)',height:'195 cm (Part 3 profil bilgisi)',personality:'Soğukkanlı, ketum ve ailesine bağlı',ability:'Stand kullanıcısı',stand:{name:'Star Platinum',image:'assets/stands/star-platinum.webp',type:'Yakın menzilli güç Stand’i',description:'Jotaro’nun Stand’i; olağanüstü hız, hassasiyet ve fiziksel güç sergiler. Zamanı kısa süre durdurabildiği DIO ile karşılaşmasında ortaya çıkar.',facts:{'Yetenek':'Yüksek hız ve hassasiyet; kısa süreli zaman durdurma','Kullanıcı':'Jotaro Kujo'}},events:['Annesi Holly’yi kurtarmak için Joseph ve müttefikleriyle Mısır’a gider.','DIO’nun Stand’i The World’ün zaman durdurma gücüyle yüzleşir.','DIO’yu yenerek Kujo ailesine yönelik tehdidi sona erdirir.'],image:null,source:'Manga/anime: Stardust Crusaders (Part 3); resmî JoJo portalı.'},
 {id:'dio-part3',name:'DIO',part:3,role:'Baş düşman · Stardust Crusaders',intro:'Jonathan’ın bedenini ele geçiren Dio Brando, bir asır sonra yeniden ortaya çıkar.',birth:'Kaynaklarda belirtilmemiş',height:'195 cm (Part 3 profil bilgisi)',personality:'Baskıcı, zeki ve kendinden emin',ability:'Vampir güçleri ve Stand kullanımı',stand:{name:'The World',type:'Yakın menzilli güç Stand’i',description:'DIO’nun Stand’i zamanı durdurabilir; DIO bu aralıkta çevresindekilere karşı hareket eder.',facts:{'Yetenek':'Zamanı durdurma','Kullanıcı':'DIO'}},events:['Jonathan’ın bedenini kullanarak deniz tabanındaki tabutundan çıkar.','Mısır’da takipçilerini toplar ve Joestar ailesini kendine çeker.','Jotaro ile yaptığı son mücadelede yenilir.'],image:null,source:'Manga/anime: Stardust Crusaders (Part 3).'},
 {id:'josuke-higashikata',name:'Josuke Higashikata',part:4,role:'JoJo · Diamond is Unbreakable',intro:'Morioh’da yaşayan Josuke, kasabasını tehdit eden seri katili durdurmak için arkadaşlarıyla harekete geçer.',birth:'1983 (doğum günü belirtilmemiş)',height:'Kaynaklarda belirtilmemiş',personality:'İyiliksever, cesur; saçına hakaret edilmesine öfkelenir',ability:'Stand kullanıcısı',stand:{name:'Crazy Diamond',image:'assets/stands/crazy-diamond.webp',type:'Yakın menzilli güç Stand’i',description:'Dokunduğu nesne ve canlıları, Josuke hariç, önceki hâllerine geri döndürebilir. İyileştirme ve onarma işlevi görür; ölüleri diriltemez.',facts:{'Yetenek':'Onarma ve önceki hâle döndürme','Kullanıcı':'Josuke Higashikata'}},events:['Jotaro’nun ziyaretiyle Josuke’nin Stand gücü ve DIO bağlantısı açığa çıkar.','Morioh’daki Stand kullanıcıları ve Yoshikage Kira ile mücadele eder.','Kasabasını korumak için müttefikleriyle birlikte Kira’yı durdurur.'],image:null,source:'Manga/anime: Diamond is Unbreakable (Part 4).'},
 {id:'yoshikage-kira',name:'Yoshikage Kira',part:4,role:'Baş düşman · Diamond is Unbreakable',intro:'Morioh’da kimliğini gizleyerek sakin bir yaşam sürmek isteyen seri katil.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Gizliliğe düşkün, soğukkanlı ve şiddet eğilimli',ability:'Stand kullanıcısı',stand:{name:'Killer Queen',type:'Yakın menzilli Stand',description:'Dokunduğu hedefleri bombaya dönüştürüp patlatabilir. Hikâye boyunca ek yetenekleri de ortaya çıkar.',facts:{'Yetenek':'Temasla bombaya dönüştürme; ek bomba yetenekleri','Kullanıcı':'Yoshikage Kira'}},events:['Morioh sakinlerinin kaybolmasıyla bağlantısı ortaya çıkar.','Josuke ve müttefikleri tarafından kimliği açığa çıkarılır.','Şehrin sakinlerini hedef alan planı başarısız olur.'],image:null,source:'Manga/anime: Diamond is Unbreakable (Part 4).'},
 {id:'giorno-giovanna',name:'Giorno Giovanna',part:5,role:'JoJo · Golden Wind',intro:'İtalya’da yaşayan Giorno, mafyanın içine girerek “Gang-Star” olma ve örgütü değiştirme hedefi taşır.',birth:'16 Nisan 1985',height:'Kaynaklarda belirtilmemiş',personality:'Kararlı, merhametli ve stratejik',ability:'Stand kullanıcısı',stand:{name:'Gold Experience',image:'assets/stands/gold-experience.webp',type:'Yakın menzilli güç Stand’i',description:'Cansız nesnelere yaşam verebilir. Gelişen yetenekleri çatışmalar sırasında gösterilir.',facts:{'Yetenek':'Cansız nesnelere yaşam verme','Kullanıcı':'Giorno Giovanna'}},events:['Bruno Bucciarati’nin ekibine katılır ve örgütün liderine ulaşmaya çalışır.','Ekip, patronun kimliğini ve planını araştırırken ihanetle karşılaşır.','Requiem gücüyle patronu yener ve Passione’nin başına geçer.'],image:null,source:'Manga/anime: Golden Wind (Part 5).'},
 {id:'bruno-bucciarati',name:'bruno-bucciarati',name:'Bruno Bucciarati',part:5,role:'Ekip lideri · Golden Wind',intro:'Passione içinde görev yapan Bruno, Giorno’nun ekibine liderlik eder.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Görev bilinci yüksek, şefkatli ve cesur',ability:'Stand kullanıcısı',stand:{name:'Sticky Fingers',type:'Yakın menzilli Stand',description:'Temas ettiği yüzeylere fermuarlar açarak nesneleri ayırabilir, erişim sağlayabilir ve hareket edebilir.',facts:{'Yetenek':'Yüzey ve nesnelere fermuar açma','Kullanıcı':'Bruno Bucciarati'}},events:['Giorno’nun hedefini sınar ve onu ekibine kabul eder.','Patronun kızını koruma görevini üstlenerek ekibiyle karşı karşıya gelir.','Giorno ve ekibiyle birlikte Passione liderliğine karşı savaşır.'],image:null,source:'Manga/anime: Golden Wind (Part 5).'},
 {id:'jolyne-cujoh',name:'Jolyne Cujoh',part:6,role:'JoJo · Stone Ocean',intro:'Jotaro’nun kızı Jolyne, işlemediğini söylediği bir suçtan hapse girer ve Green Dolphin Street Hapishanesi’nde Stand gücünü keşfeder.',birth:'1992 (doğum günü belirtilmemiş)',height:'174.5 cm',personality:'İnatçı, cesur ve korumacı',ability:'Stand kullanıcısı',stand:{name:'Stone Free',image:'assets/stands/stone-free.webp',type:'Yakın menzilli güç Stand’i',description:'Jolyne’nin bedenini ipliğe dönüştürmesine ve bu ipliği kontrol etmesine olanak verir.',facts:{'Yetenek':'Bedenini ipliğe açma ve ipliği kontrol etme','Kullanıcı':'Jolyne Cujoh'}},events:['Jotaro’nun anılarını geri almak için hapishanede mücadele eder.','Enrico Pucci’nin planını öğrenir ve müttefikleriyle onu durdurmaya çalışır.','Evrenin kaderini belirleyen son çatışmada babası ve dostlarının mirasını taşır.'],image:null,source:'Manga/anime: Stone Ocean (Part 6).'},
 {id:'enrico-pucci',name:'Enrico Pucci',part:6,role:'Baş düşman · Stone Ocean',intro:'Green Dolphin Street Hapishanesi’nde rahip olan Pucci, DIO ile kurduğu bağ doğrultusunda “Cennet” planını tamamlamaya çalışır.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'İnançlı, kararlı ve amaçları uğruna acımasız',ability:'Stand kullanıcısı',stand:{name:'Whitesnake',type:'Uzak menzilli Stand',description:'Hedeflerden anı ve Stand yeteneklerini diskler olarak çıkarabilir. Pucci’nin Stand’i hikâye ilerledikçe evrilir.',facts:{'Yetenek':'Anı ve Stand disklerini çıkarma','Kullanıcı':'Enrico Pucci'}},events:['DIO’dan “Cennet”e ulaşma planını öğrenir.','Jotaro’nun anı diskini alıp planını yürütmeye çalışır.','Jolyne ve müttefikleriyle evrenin geleceği için karşı karşıya gelir.'],image:null,source:'Manga/anime: Stone Ocean (Part 6).'},
 {id:'johnny-joestar',name:'Johnny Joestar',part:7,role:'JoJo · Steel Ball Run',intro:'Eski bir jokey olan Johnny, Gyro Zeppeli ile Amerika kıtasını aşan Steel Ball Run yarışına katılır.',birth:'1872 (doğum günü belirtilmemiş)',height:'Kaynaklarda belirtilmemiş',personality:'İçe dönük, kararlı ve zamanla daha fedakâr',ability:'Spin (Dönüş) tekniğini öğrenir',stand:{name:'Tusk',type:'Gelişen Stand',description:'Johnny’nin tırnaklarını mermi gibi fırlatmasını sağlar. Spin bilgisini geliştirdikçe farklı aşamalara evrilir.',facts:{'Yetenek':'Tırnak mermileri ve Spin ile evrilen aşamalar','Kullanıcı':'Johnny Joestar'}},events:['Bacaklarını kullanamayan Johnny, Gyro’nun Spin tekniğinin ardındaki sırrı keşfetmeye çalışır.','Yarışın, Kutsal Ceset parçalarını toplamakla bağlantısını öğrenir.','Valentine’ın planına karşı Gyro’yla birlikte mücadele eder.'],image:null,source:'Manga: Steel Ball Run (Part 7); resmî JoJo portalı.'},
 {id:'gyro-zeppeli',name:'gyro-zeppeli',name:'Gyro Zeppeli',part:7,role:'Yarışçı · Steel Ball Run',intro:'Napoli’den gelen cellat ve yarışçı Gyro, Steel Ball Run’a kendi amacı doğrultusunda katılır.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Neşeli, kendine güvenen ve merhametli',ability:'Spin tekniği',stand:{name:'Ball Breaker',type:'Spin ile ortaya çıkan yetenek',description:'Altın Dikdörtgen ve Spin’in ustalığıyla ortaya çıkan güç; hedefte yaşlandırıcı bir etki oluşturabilir.',facts:{'Yetenek':'Ustalıkla uygulanan Spin’in saldırı biçimi','Kullanıcı':'Gyro Zeppeli'}},events:['Johnny’ye Spin’i öğretir ve yarış boyunca onunla ortaklık kurar.','Yarışın ardındaki Kutsal Ceset mücadelesine dahil olur.','Valentine’a karşı çatışmada Johnny’nin yolunu etkileyen kritik bir rol oynar.'],image:null,source:'Manga: Steel Ball Run (Part 7).'},
 {id:'josuke-gappy',name:'Josuke Higashikata (Gappy)',part:8,role:'JoJo · JoJolion',intro:'2011’de Morioh’da, kim olduğunu bilmeden bir duvarın yanında bulunur; geçmişini araştırırken Higashikata ailesine yaklaşır.',birth:'Bilinmiyor (kimliği ve geçmişi araştırılır)',height:'Kaynaklarda belirtilmemiş',personality:'Meraklı, doğrudan ve başkalarına karşı duyarlı',ability:'Stand kullanıcısı',stand:{name:'Soft & Wet',type:'Yakın menzilli Stand',description:'Kabarcıklar üretir. İlk başta bu kabarcıkların temas ettikleri şeylerden özellik çalabildiği görülür; gerçek doğası gizem taşır.',facts:{'Yetenek':'Kabarcıklar ve özellikleri geçici olarak alma','Kullanıcı':'Josuke Higashikata'}},events:['Yasuho Hirose tarafından bulunur ve “Gappy” lakabını alır.','Kimliğini ve geçmişini Higashikata ailesiyle bağlantılı sırlar üzerinden araştırır.','Morioh’daki Rokakaka meyvesi ve felaket zincirinin ardındaki gerçeğe ulaşmaya çalışır.'],image:null,source:'Manga: JoJolion (Part 8).'},
 {id:'jodio-joestar',name:'Jodio Joestar',part:9,role:'JoJo · The JOJOLands',intro:'Hawaii, Oʻahu’da yaşayan 15 yaşındaki Jodio, ailesini zengin etme hedefiyle yeraltı dünyasında işlere karışır.',birth:'15 yaşında (doğum tarihi belirtilmemiş)',height:'Kaynaklarda belirtilmemiş',personality:'Soğukkanlı, hesapçı; “mekanizma” fikrine odaklı',ability:'Stand kullanıcısı',stand:{name:'November Rain',type:'Yakın menzilli Stand',description:'Yağmur damlalarını belirli bir alan içinde aşağı doğru yöneltip yoğunlaştırabilir; damlaların etkisi hedefler üzerinde ağır basınç yaratır.',facts:{'Yetenek':'Kontrollü ve ağır basınçlı yağmur damlaları','Kullanıcı':'Jodio Joestar'}},events:['Annesi Meryl Mei Qi’nin ekibiyle kaçakçılık işlerinde çalışır.','Dragona, Usagi ve Paco ile birlikte Hawaii’de değerli bir elmasın çalınması görevini üstlenir.','Part 9 devam etmektedir; karakterin sonraki hikâyesi yeni bölümlerle güncellenebilir.'],image:null,source:'Manga: The JOJOLands (Part 9), yayımlanmış bölümler; resmî JoJo portalı.'},
 {id:'dragona-joestar',name:'Dragona Joestar',part:9,role:'Jodio’nun kardeşi · The JOJOLands',intro:'Jodio’nun ağabeyi ve ekibin bir üyesi. Part 9’un Hawaii’deki soygun görevinde yer alır.',birth:'18 yaşında (doğum tarihi belirtilmemiş)',height:'Kaynaklarda belirtilmemiş',personality:'Nazik, kendine güvenen ve ekip çalışmasına yatkın',ability:'Stand kullanıcısı',stand:{name:'Smooth Operators',type:'Birden çok küçük Stand birimi',description:'Küçük birimlerini yüzeyler boyunca hareket ettirebilir; cilt ve yüzey özelliklerini kaydırıp yeniden konumlandırabilir.',facts:{'Yetenek':'Yüzey ve özellikleri kaydırıp yeniden konumlandırma','Kullanıcı':'Dragona Joestar'}},events:['Jodio’nun kardeşidir ve Meryl Mei Qi’nin ekibinde çalışır.','Jodio ve diğer ekip üyeleriyle birlikte elmas soygununa katılır.','Part 9 devam etmektedir; yeni gelişmeler manga kayıtlarıyla eklenebilir.'],image:null,source:'Manga: The JOJOLands (Part 9), yayımlanmış bölümler; resmî JoJo portalı.'},
 {id:'paco-lovelantes',name:'Paco Lovelantes',part:9,role:'Ekip üyesi · The JOJOLands',intro:'Jodio ve Dragona’nın arkadaşı ve ekibinin bir parçası.',birth:'19 yaşında (doğum tarihi belirtilmemiş)',height:'Kaynaklarda belirtilmemiş',personality:'Atılgan ve pratik',ability:'Stand kullanıcısı',stand:{name:'The Hustle',type:'Vücut temelli Stand',description:'Paco’nun kaslarını kontrol etmesini, kas dokusuyla nesneleri kavrayıp vücudunun farklı bölgelerine tutunmasını sağlar.',facts:{'Yetenek':'Kas dokusuyla kavrama ve vücuda tutunma','Kullanıcı':'Paco Lovelantes'}},events:['Meryl Mei Qi’nin ekibinde Jodio ve Dragona’yla birlikte çalışır.','Elmas soygununa ve ekibin Hawaii’deki görevlerine katılır.','Part 9 devam etmektedir.'],image:null,source:'Manga: The JOJOLands (Part 9), yayımlanmış bölümler.'},
 {id:'usagi-alohaoe',name:'Usagi Alohaoe',part:9,role:'Ekip üyesi · The JOJOLands',intro:'Jodio’nun ekibiyle bağlantılı genç Stand kullanıcısı; elmas görevinde onlara eşlik eder.',birth:'17 yaşında (doğum tarihi belirtilmemiş)',height:'Kaynaklarda belirtilmemiş',personality:'Dağınık, kaygılı ve yaratıcı',ability:'Stand kullanıcısı',stand:{name:'The Matte Kudasai',type:'İstek taklit eden Stand',description:'Bir başkasının dile getirdiği isteğin nesnesine dönüşebilir; gücün kullanımı isteğin sahibine bağlıdır.',facts:{'Yetenek':'Başkasının ifade ettiği isteğe dönüşme','Kullanıcı':'Usagi Alohaoe'}},events:['Jodio ve Dragona ile Hawaii’deki görevde birlikte çalışır.','Ekiple birlikte elmas soygununun içine çekilir.','Part 9 devam etmektedir.'],image:null,source:'Manga: The JOJOLands (Part 9), yayımlanmış bölümler.'}
];
window.JOJO_PARTS = [{id:1,label:'PHANTOM BLOOD'},{id:2,label:'BATTLE TENDENCY'},{id:3,label:'STARDUST CRUSADERS'},{id:4,label:'DIAMOND IS UNBREAKABLE'},{id:5,label:'GOLDEN WIND'},{id:6,label:'STONE OCEAN'},{id:7,label:'STEEL BALL RUN'},{id:8,label:'JOJOLION'},{id:9,label:'THE JOJOLANDS'}];

window.JOJO_CHARACTERS.push(
 {id:'erina-pendleton',name:'Erina Pendleton',part:1,role:'Müttefik · Phantom Blood',intro:'Jonathan’ın çocukluk arkadaşı ve hayat arkadaşı; Joestar ailesinin sonraki kuşaklarında da önemli bir yeri vardır.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Şefkatli, cesur ve dirençli',ability:'Özel yeteneği belirtilmemiş',stand:null,events:['Jonathan’la çocukluklarından itibaren bağ kurar.','Dio’nun saldırılarına rağmen Jonathan’ın yanında durur.','Jonathan’ın ölümünden sonra torunu Joseph’i yetiştirir.'],image:null,source:'Manga: Phantom Blood (Part 1).'},
 {id:'will-zeppeli',name:'Will A. Zeppeli',part:1,role:'Hamon ustası · Phantom Blood',intro:'Taş Maske’nin tehdidine karşı Hamon çalışmış ve Jonathan’a bu tekniği öğreten gezgin.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Bilge, neşeli ve özverili',ability:'Hamon (Ripple)',stand:null,events:['Taş Maske’nin gücünü araştırırken Hamon öğrenir.','Jonathan’a Hamon tekniğini öğretir.','Dio’ya karşı verilen mücadelede hayatını feda eder.'],image:null,source:'Manga: Phantom Blood (Part 1).'},
 {id:'robert-speedwagon',name:'Robert E. O. Speedwagon',part:1,role:'Joestar müttefiki · Phantom Blood',intro:'Jonathan’la karşılaşması hayatının yönünü değiştirir; ileride Speedwagon Vakfı’nı kurar.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Sadık, cesur ve cömert',ability:'Özel yeteneği belirtilmemiş',stand:null,events:['Jonathan’ın karakterinden etkilenerek onun yanında yer alır.','Dio’ya karşı mücadelede Jonathan’a yardım eder.','Speedwagon Vakfı’nı kurarak sonraki Joestar kuşaklarına destek olur.'],image:null,source:'Manga: Phantom Blood ve sonraki Part’lar.'},
 {id:'bruford',name:'Bruford',part:1,role:'Dio’nun savaşçısı · Phantom Blood',intro:'Dio tarafından yeniden canlandırılan, geçmişte cesaretiyle tanınan bir şövalye.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Onurlu ve savaşçı',ability:'Zombi gücü; kılıç kullanımı',stand:null,events:['Dio’nun emriyle Jonathan’la savaşır.','Mücadele sırasında şövalye onurunu yeniden hatırlar.','Jonathan’a Luck ile Pluck adlı kılıcını bırakarak ölür.'],image:null,source:'Manga: Phantom Blood (Part 1).'},
 {id:'lisa-lisa',name:'Lisa Lisa',part:2,role:'Hamon ustası · Battle Tendency',intro:'Joseph ve Caesar’ın Hamon eğitmeni; Sütun Adamları’na karşı direnişin önemli isimlerinden.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Disiplinli, kendinden emin ve kararlı',ability:'Hamon (Ripple)',stand:null,events:['Joseph ve Caesar’ı Hamon eğitimi için yönlendirir.','Sütun Adamları’na karşı savaşta yer alır.','Geçmişinin Joestar ailesiyle bağlantısı ortaya çıkar.'],image:null,source:'Manga: Battle Tendency (Part 2).'},
 {id:'kars',name:'Kars',part:2,role:'Baş düşman · Battle Tendency',intro:'Sütun Adamları’nın lideri; Güneş’in zayıflığını ortadan kaldırıp nihai yaşam formuna ulaşmayı amaçlar.',birth:'İnsanlık tarihinden önce (kesin tarih belirtilmemiş)',height:'Kaynaklarda belirtilmemiş',personality:'Zeki, acımasız ve amacına bağlı',ability:'Sütun Adamı fizyolojisi; Taş Maske',stand:null,events:['Taş Maske’nin kökenini ve gücünü bilen Sütun Adamları’na liderlik eder.','Hamon kullanıcılarıyla ve Joseph’le çatışır.','Nihai yaşam formuna dönüşür; uzaya savrulmasının ardından Dünya’ya dönemez.'],image:null,source:'Manga: Battle Tendency (Part 2).'},
 {id:'wamuu',name:'Wamuu',part:2,role:'Sütun Adamı · Battle Tendency',intro:'Kars’a bağlı, savaşçı onuruna önem veren güçlü Sütun Adamı.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Onurlu, disiplinli ve savaşçı',ability:'Sütun Adamı yetenekleri; rüzgârı kontrol etme',stand:null,events:['Joseph ve Caesar’la karşılaşır.','Joseph’le ölümüne bir düello yapar.','Düellonun sonucunu kabul ederek onurlu biçimde ölür.'],image:null,source:'Manga: Battle Tendency (Part 2).'},
 {id:'esidisi',name:'Esidisi',part:2,role:'Sütun Adamı · Battle Tendency',intro:'Kars’ın müttefiki olan Sütun Adamı; bedensel kontrol ve ısı temelli saldırılar kullanır.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Kurnaz, öfkeli ve kararlı',ability:'Sütun Adamı yetenekleri; ısı ve kan damarlarını kullanma',stand:null,events:['Kars ve Wamuu’yla birlikte Aja Taşı’nın peşine düşer.','Joseph’le çatışır ve yenilir.'],image:null,source:'Manga: Battle Tendency (Part 2).'},
 {id:'rudol-von-stroheim',name:'Rudol von Stroheim',part:2,role:'Asker · Battle Tendency',intro:'Alman ordusunda görevli subay; Sütun Adamları tehdidi karşısında Joseph’le geçici ittifak kurar.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Gururlu, sert ve görevine bağlı',ability:'Sibernetik beden ve askerî donanım',stand:null,events:['Sütun Adamları hakkındaki bilgileri Joseph’le paylaşır.','Kars’la savaşmak için sibernetik bir bedene dönüştürülür.','Kars’a karşı mücadelede yeniden Joseph’e yardım eder.'],image:null,source:'Manga: Battle Tendency (Part 2).'}
);

window.JOJO_CHARACTERS.push(
 {id:'meryl-mei-qi',name:'Meryl Mei Qi',part:9,role:'Jodio’nun ekibinin lideri · The JOJOLands',intro:'Jodio’nun okul müdürü ve bir butiğin sahibi; Hawaii’deki yeraltı ekibinin görevlerini yönetir.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Girişken, hesapçı ve otoriter',ability:'Stand gücü kaynaklarda belirtilmemiş',stand:null,events:['Jodio, Dragona, Paco ve Usagi’nin ekibine liderlik eder.','Ekipten Japon bir ziyaretçinin elmasını çalmalarını ister.','Lava Rock’ın gücünü kullanarak HOWLER şirketinin arazilerine ulaşma planını geliştirir.','Part 9 devam ediyor; yeni bilgiler yayımlandıkça kayıt güncellenebilir.'],image:null,source:'Manga: The JOJOLands (Part 9); resmî JoJo portalı.'},
 {id:'charming-man',name:'Charming Man',part:9,role:'Jodio’nun müttefiki · The JOJOLands',intro:'Kardeşinin kayboluşuyla ilgili araştırma sırasında Jodio’nun ekibiyle karşılaşan genç adam.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Kurnaz, esprili ve kardeşine bağlı',ability:'Stand kullanıcısı',stand:{name:'Bigmouth Strikes Again',type:'Kum temelli Stand',description:'Kum benzeri parçacıkları kullanarak bedenini ve görünüşünü değiştirebilir; kesin sınırları hikâye ilerledikçe açığa çıkar.',facts:{'Yetenek':'Kum benzeri parçacıklarla görünüş ve beden değiştirme','Kullanıcı':'Charming Man'}},events:['Kardeşi Mauka’nın kaybolmasının izini sürerken Jodio’nun ekibiyle karşılaşır.','HOWLER arazileri çevresindeki çatışmalarda ekiple ortak hareket eder.','Part 9 devam ediyor; yetenek ve hikâyesi yeni bölümlerle genişleyebilir.'],image:null,source:'Manga: The JOJOLands (Part 9), yayımlanmış bölümler.'}
);

window.JOJO_CHARACTERS.push(
 {id:'funny-valentine',name:'Funny Valentine',part:7,role:'Baş düşman · Steel Ball Run',intro:'Amerika Birleşik Devletleri’nin 23. Başkanı; Kutsal Ceset parçalarını ülkesinin gücünü artırmak için arar.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Yurtsever, stratejik ve amacında acımasız',ability:'Stand kullanıcısı',stand:{name:'D4C (Dirty Deeds Done Dirt Cheap)',type:'Boyutlar arası Stand',description:'İki yüzey arasına sıkışma yoluyla paralel boyutlar arasında hareket edebilir ve alternatif dünyalardan kişileri getirebilir.',facts:{'Yetenek':'Paralel boyutlara geçiş','Kullanıcı':'Funny Valentine'}},events:['Steel Ball Run yarışını ve Kutsal Ceset arayışını yönlendirir.','Johnny ve Gyro’nun Kutsal Ceset parçalarını toplamasını engellemeye çalışır.','Love Train gücünü kullanır; Johnny’nin Tusk Act 4 saldırısıyla yenilir.'],image:null,source:'Manga: Steel Ball Run (Part 7).'},
 {id:'diego-brando',name:'Diego Brando',part:7,role:'Rakip jokey · Steel Ball Run',intro:'İngiltere’den gelen yetenekli jokey; yarışta kendi hedefleri için mücadele eder.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Hırslı, hesapçı ve rekabetçi',ability:'Stand kullanıcısı',stand:{name:'Scary Monsters',type:'Dönüşüm Stand’i',description:'Dinozorlaştırma yeteneği verir; Diego ve etkilediği canlılar dinozor özellikleri kazanabilir.',facts:{'Yetenek':'Dinozorlaştırma','Kullanıcı':'Diego Brando'}},events:['Steel Ball Run’da Johnny ve Gyro’nun rakibi olur.','Valentine tarafından Kutsal Ceset mücadelesinde kullanılır.','Alternatif dünyadaki Diego, Johnny’nin son rakiplerinden biri olarak ortaya çıkar.'],image:null,source:'Manga: Steel Ball Run (Part 7).'},
 {id:'lucy-steel',name:'Lucy Steel',part:7,role:'Yarışın içindeki müttefik · Steel Ball Run',intro:'Steel’in genç eşi; Valentine’ın planını öğrendikten sonra yarışın siyasi entrikalarına dahil olur.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Cesur, kararlı ve fedakâr',ability:'İlk başta Stand gücü göstermez',stand:null,events:['Kocasının yarışla ilgili görevinde yanında yer alır.','Valentine’ın Kutsal Ceset arayışını öğrenir ve ona karşı hareket eder.','D4C’yi etkisizleştirmeye yönelik kritik bir rol üstlenir.'],image:null,source:'Manga: Steel Ball Run (Part 7).'},
 {id:'hot-pants',name:'Hot Pants',part:7,role:'Yarışçı ve rahibe · Steel Ball Run',intro:'Steel Ball Run’a Hot Pants adıyla katılan gizemli yarışçı; Kutsal Ceset parçalarını arar.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Ketum, disiplinli ve korumacı',ability:'Stand kullanıcısı',stand:{name:'Cream Starter',type:'Vücut değiştiren Stand',description:'Sprey benzeri biçimde kullanılır; et ve dokuyu püskürterek bedenleri değiştirebilir ve iyileştirebilir.',facts:{'Yetenek':'Et ve dokuyu püskürtme; bedenleri değiştirme','Kullanıcı':'Hot Pants'}},events:['Yarışta kimliğini gizleyerek ilerler.','Kutsal Ceset parçalarını kiliseye ulaştırmaya çalışır.','Valentine’a karşı Johnny ve Gyro’ya yardım eder.'],image:null,source:'Manga: Steel Ball Run (Part 7).'},
 {id:'mountain-tim',name:'Mountain Tim',part:7,role:'Kovboy ve yarışçı · Steel Ball Run',intro:'Steel Ball Run yarışına katılan kovboy ve iz sürücü.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Dürüst, yardımsever ve cesur',ability:'Stand kullanıcısı',stand:{name:'Oh! Lonesome Me',type:'İp temelli Stand',description:'Tim’in bedenini iplere ayırıp uzatmasına ve ipleri kullanarak hareket etmesine imkân verir.',facts:{'Yetenek':'Bedeni ve uzuvları ip gibi kullanma','Kullanıcı':'Mountain Tim'}},events:['Yarış sırasında Johnny ve Gyro’yla karşılaşır.','Lucy Steel’i korumaya çalışır.','Valentine’ın adamlarıyla çatışmasında hayatını kaybeder.'],image:null,source:'Manga: Steel Ball Run (Part 7).'},
 {id:'ringo-roadagain',name:'Ringo Roadagain',part:7,role:'Silahşor · Steel Ball Run',intro:'Kendi felsefesini “gerçek erkeklik” fikrine dayandıran silahşor ve Stand kullanıcısı.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Disiplinli, soğukkanlı ve sınayıcı',ability:'Stand kullanıcısı',stand:{name:'Mandom',type:'Zaman geri sarma Stand’i',description:'Altı saniyelik süreyi geri sarabilir; Ringo bu gücü çatışmalarda konumunu ve hamlelerini yeniden düzenlemek için kullanır.',facts:{'Yetenek':'Zamanı altı saniye geri alma','Kullanıcı':'Ringo Roadagain'}},events:['Gyro ve Johnny’yi kendi çiftliğinde düelloya zorlar.','Gyro’yla ölümüne karşılaşmasında onu sınar.','Gyro tarafından yenilir.'],image:null,source:'Manga: Steel Ball Run (Part 7).'},
 {id:'yasuho-hirose',name:'Yasuho Hirose',part:8,role:'Josuke’nin müttefiki · JoJolion',intro:'Morioh’da Josuke’yi bulan ve kimliğini araştırmasına yardım eden genç kadın.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Meraklı, cesur ve sadık',ability:'Stand kullanıcısı',stand:{name:'Paisley Park',type:'Bilgi ve yönlendirme Stand’i',description:'Bilgi ve teknolojik sistemlerle etkileşerek Yasuho’ya seçenekler, veriler ve yön bulma desteği sunar.',facts:{'Yetenek':'Bilgi bulma ve olası yolları gösterme','Kullanıcı':'Yasuho Hirose'}},events:['Josuke’yi duvarın yanında bulur ve ona Gappy adını verir.','Kimlik araştırmasında Higashikata ailesiyle ilgili sırları ortaya çıkarır.','Tooru ve Rokakaka çevresindeki çatışmalarda Josuke’ye yardım eder.'],image:null,source:'Manga: JoJolion (Part 8).'},
 {id:'rai-mamezuku',name:'Rai Mamezuku',part:8,role:'Müttefik · JoJolion',intro:'Rokakaka bitkisi hakkında uzmanlığı bulunan meyve yetiştiricisi; Josuke ve Yasuho’yla iş birliği yapar.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Pragmatik, ketum ve kararlı',ability:'Stand kullanıcısı',stand:{name:'Doggy Style',type:'İp temelli Stand',description:'Rai’nin bedenini ip biçiminde uzatıp ayırmasına ve bu ipleri kontrol etmesine olanak verir.',facts:{'Yetenek':'Bedeni ip gibi uzatma ve kontrol etme','Kullanıcı':'Rai Mamezuku'}},events:['Rokakaka bitkisiyle ilgili bilgisini Josuke’yle paylaşır.','Josuke ve Yasuho’yla birlikte Higashikata ailesinin arazisine gider.','Tooru’yla savaşta müttefiklerine yardım eder ve hayatını kaybeder.'],image:null,source:'Manga: JoJolion (Part 8).'},
 {id:'norisuke-higashikata-iv',name:'Norisuke Higashikata IV',part:8,role:'Higashikata ailesinin reisi · JoJolion',intro:'Morioh’daki Higashikata ailesinin reisi; Josuke’yi evine alır ve aile sırlarının merkezinde bulunur.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Aile odaklı, yardımsever ve sır saklayan',ability:'Stand kullanıcısı',stand:{name:'King Nothing',type:'İz sürme Stand’i',description:'Koku ve izleri takip edebilen parçalara dönüşerek bir hedefin izini sürer.',facts:{'Yetenek':'Koku ve iz takibi','Kullanıcı':'Norisuke Higashikata IV'}},events:['Josuke’yi Higashikata evinde yaşamaya davet eder.','Ailenin Rokakaka meyvesiyle bağlantılı geçmişi açığa çıkar.','Ailesini felaketten korumaya çalışırken Tooru’yla çatışır.'],image:null,source:'Manga: JoJolion (Part 8).'},
 {id:'jobin-higashikata',name:'Jobin Higashikata',part:8,role:'Higashikata ailesi · JoJolion',intro:'Norisuke’nin büyük oğlu; ailesini kurtarma arzusuyla Rokakaka meyvesinin peşine düşer.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Hırslı, korumacı ve sonuç odaklı',ability:'Stand kullanıcısı',stand:{name:'Speed King',type:'Isı temelli Stand',description:'Dokunduğu nesnelerde ısı depolayabilir ve bu ısıyı daha sonra açığa çıkarabilir.',facts:{'Yetenek':'Isı depolama ve salma','Kullanıcı':'Jobin Higashikata'}},events:['Higashikata ailesinin geleceği için Rokakaka meyvesini kullanmayı planlar.','Josuke’nin araştırmasıyla hedefleri çatışır.','Tooru’nun felaket gücüyle karşılaşmasının ardından hayatını kaybeder.'],image:null,source:'Manga: JoJolion (Part 8).'},
 {id:'tooru',name:'Tooru',part:8,role:'Baş düşman · JoJolion',intro:'Yasuho’nun geçmişinden gelen ve Rokakaka araştırmalarının arkasında bulunan Rock Human.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Sakin, manipülatif ve kendine güvenen',ability:'Stand kullanıcısı',stand:{name:'Wonder of U',type:'Felaket temalı Stand',description:'Kullanıcısını takip etmeye veya ona yaklaşmaya çalışanlarda felaket zincirini tetikler; bu güç nedensellik ve talihsizlik üzerinden işler.',facts:{'Yetenek':'Takip girişimlerine karşı felaket zinciri','Kullanıcı':'Tooru'}},events:['Yasuho’yla geçmişte ilişkisi olmuştur.','Rokakaka meyvesi ve Locacaca 6251 araştırmasını yönetir.','Josuke ve müttefiklerinin karşı koyduğu felaket gücünün kaynağı olur.'],image:null,source:'Manga: JoJolion (Part 8).'}
);

window.JOJO_CHARACTERS.push(
 {id:'guido-mista',name:'Guido Mista',part:5,role:'Bucciarati ekibi · Golden Wind',intro:'Bucciarati’nin ekibinde görev yapan keskin nişancı; Giorno’nun örgütü değiştirme hedefini destekler.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Rahat tavırlı, cesur ve batıl inançlı',ability:'Stand kullanıcısı',stand:{name:'Sex Pistols',type:'Altı küçük Stand birimi',description:'Altı ayrı Stand birimi Mista’nın mermilerini yönlendirerek atışlarının gidişatını değiştirebilir.',facts:{'Yetenek':'Mermileri yönlendirme','Kullanıcı':'Guido Mista'}},events:['Bruno Bucciarati’nin ekibinde Giorno’yla birlikte görev yapar.','Trish’i koruma görevinde patronun emrine karşı çıkan ekibe katılır.','Diavolo’ya karşı son mücadelede Giorno’nun yanında savaşır.'],image:null,source:'Manga/anime: Golden Wind (Part 5).'},
 {id:'narancia-girga',name:'Narancia Ghirga',part:5,role:'Bucciarati ekibi · Golden Wind',intro:'Bruno’nun ekibine katılan genç; hava keşfi ve saldırılarında Stand’ini kullanır.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Duygusal, sadık ve neşeli',ability:'Stand kullanıcısı',stand:{name:'Aerosmith',type:'Uzaktan keşif ve saldırı Stand’i',description:'Miniatür bir uçak biçimindedir; makineli tüfek ve bombalar taşır, karbondioksiti algılayan radarıyla canlıları izler.',facts:{'Yetenek':'Uçan saldırı aracı ve CO₂ radarı','Kullanıcı':'Narancia Ghirga'}},events:['Bucciarati’nin ekibine katılarak Giorno’yla birlikte çalışır.','Trish’i korumak için patronun emirlerine karşı çıkanlara destek olur.','Diavolo’nun saldırısı sırasında hayatını kaybeder.'],image:null,source:'Manga/anime: Golden Wind (Part 5).'},
 {id:'leone-abbacchio',name:'Leone Abbacchio',part:5,role:'Bucciarati ekibi · Golden Wind',intro:'Geçmişinde polis memurluğu bulunan, Bucciarati’nin ekibinde görev yapan Stand kullanıcısı.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Kuşkucu, sert ve sadık',ability:'Stand kullanıcısı',stand:{name:'Moody Blues',type:'İz sürme Stand’i',description:'Geçmişte yaşanmış olayları zaman çizelgesi içinde yeniden canlandırarak inceleyebilir.',facts:{'Yetenek':'Geçmiş olayları yeniden oynatma','Kullanıcı':'Leone Abbacchio'}},events:['Bucciarati’nin ekibinde Giorno’nun yeteneğine kuşkuyla yaklaşır.','Patronun kimliğini araştırmak için geçmişteki olayları yeniden canlandırır.','Araştırması sırasında Diavolo tarafından öldürülür.'],image:null,source:'Manga/anime: Golden Wind (Part 5).'},
 {id:'pannacotta-fugo',name:'Pannacotta Fugo',part:5,role:'Bucciarati ekibi · Golden Wind',intro:'Bucciarati’nin ekibinin zeki üyesi; Giorno’nun patrona karşı isyanında ekibin geri kalanından ayrılır.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Zeki, çabuk öfkelenen ve çatışmalı',ability:'Stand kullanıcısı',stand:{name:'Purple Haze',type:'Yakın menzilli Stand',description:'Kollarındaki kapsüller kırıldığında ölümcül virüs yayan sis oluşturur; virüs ayrım gözetmeden etkiler.',facts:{'Yetenek':'Kapsüllerden yayılan ölümcül virüs','Kullanıcı':'Pannacotta Fugo'}},events:['Giorno’nun ekibine katılmasına karşı sınama sürecinde yer alır.','Trish’i patrona teslim etmeyi reddeden ekibin kararından ayrılır.','Hikâyenin geri kalanında ekiple yeniden bir araya gelmez.'],image:null,source:'Manga/anime: Golden Wind (Part 5).'},
 {id:'trish-una',name:'Trish Una',part:5,role:'Passione hedefi · Golden Wind',intro:'Passione patronunun kızı; Bruno Bucciarati’nin ekibi tarafından korunur.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Başlangıçta mesafeli; zamanla cesur ve kararlı',ability:'Stand kullanıcısı',stand:{name:'Spice Girl',type:'Yakın menzilli Stand',description:'Dokunduğu nesneleri yumuşak ve esnek hâle getirebilir; bu sayede sert yüzeyler darbeleri emer.',facts:{'Yetenek':'Nesneleri yumuşatıp esnetme','Kullanıcı':'Trish Una'}},events:['Bucciarati’nin ekibi tarafından babasına götürülürken korunur.','Patronun gerçek niyetini öğrenince ekiple birlikte ona karşı çıkar.','Diavolo’ya karşı verilen mücadelede kendi Stand gücünü uyandırır.'],image:null,source:'Manga/anime: Golden Wind (Part 5).'},
 {id:'diavolo',name:'Diavolo',part:5,role:'Baş düşman · Golden Wind',intro:'Passione’nin gizemli lideri; kimliğini ve geçmişini herkesten saklamaya çalışır.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Paranoyak, acımasız ve kontrol takıntılı',ability:'Stand kullanıcısı',stand:{name:'King Crimson',type:'Zaman yeteneğine sahip Stand',description:'Kısa bir zaman aralığını silerek diğerlerinin eylemlerinin sonucunu değiştirebilir; Epitaph yaklaşan geleceği görür.',facts:{'Yetenek':'Zaman aralığını silme ve yakın geleceği görme','Kullanıcı':'Diavolo'}},events:['Trish’in babası olduğunu gizleyerek onu ortadan kaldırmaya çalışır.','Bruno’nun ekibinin isyanından sonra Giorno’yla karşı karşıya gelir.','Gold Experience Requiem’in saldırısından sonra sonu gelmeyen ölümler yaşar.'],image:null,source:'Manga/anime: Golden Wind (Part 5).'},
 {id:'ermes-costello',name:'Ermes Costello',part:6,role:'Jolyne’nin müttefiki · Stone Ocean',intro:'Green Dolphin Street Hapishanesi’nde Jolyne’yle arkadaş olan mahkûm.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Gözü pek, kararlı ve ailesine bağlı',ability:'Stand kullanıcısı',stand:{name:'Kiss',type:'Yakın menzilli Stand',description:'Nesnelerin üzerine çıkartma yerleştirir; çıkartma kaldırıldığında kopyalar yeniden birleşirken çarpışma etkisi yaratır.',facts:{'Yetenek':'Çıkartmayla nesne kopyalama ve birleştirme','Kullanıcı':'Ermes Costello'}},events:['Jolyne’yle hapishanede tanışır ve ona yardım eder.','Kız kardeşi Gloria’nın intikamını almak için hapishaneye girmiştir.','Pucci’ye karşı Jolyne ve diğer mahkûmlarla birlikte savaşır.'],image:null,source:'Manga/anime: Stone Ocean (Part 6).'},
 {id:'foo-fighters',name:'Foo Fighters',part:6,role:'Jolyne’nin müttefiki · Stone Ocean',intro:'Plankton kolonisi ve bir Stand’in birleşmesiyle oluşan bilinçli varlık.',birth:'Bilinmiyor',height:'Kaynaklarda belirtilmemiş',personality:'Meraklı, sadık ve insan olmayı öğrenen',ability:'Plankton kolonisi; Stand kullanıcısı',stand:{name:'Foo Fighters',type:'Plankton temelli Stand',description:'Plankton kolonisini kontrol ederek beden oluşturur; suya ve neme ihtiyaç duyar, yaralarını planktonla onarabilir.',facts:{'Yetenek':'Plankton bedenini kontrol etme ve yenileme','Kullanıcı':'Foo Fighters'}},events:['Pucci’nin koruduğu Stand diskinden doğar.','Jolyne’yle karşılaştıktan sonra onun müttefiki olur.','Nihai çatışmalarda Emporio’yu koruyarak hayatını kaybeder.'],image:null,source:'Manga/anime: Stone Ocean (Part 6).'},
 {id:'weather-report',name:'Weather Report',part:6,role:'Jolyne’nin müttefiki · Stone Ocean',intro:'Green Dolphin Street Hapishanesi’nde hafızasını kaybetmiş olarak yaşayan mahkûm.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Sessiz, içine kapanık ve koruyucu',ability:'Stand kullanıcısı',stand:{name:'Weather Report',type:'Hava kontrolü Stand’i',description:'Havayı ve atmosfer olaylarını kontrol edebilir. Belleğine bağlı gizli yeteneği Heavy Weather, optik yanılsamalar oluşturur.',facts:{'Yetenek':'Hava olaylarını kontrol etme; Heavy Weather','Kullanıcı':'Weather Report'}},events:['Jolyne’nin Pucci’nin planına karşı mücadelesine katılır.','Geçmişini ve Pucci’yle olan aile bağını yeniden keşfeder.','Stand diskini Emporio’ya ulaştırdıktan sonra hayatını kaybeder.'],image:null,source:'Manga/anime: Stone Ocean (Part 6).'},
 {id:'narciso-anasui',name:'Narciso Anasui',part:6,role:'Jolyne’nin müttefiki · Stone Ocean',intro:'Jolyne’ye yardım ederek onunla birlikte hapishaneden kaçmayı amaçlayan mahkûm.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Yoğun, kararlı ve Jolyne’ye bağlı',ability:'Stand kullanıcısı',stand:{name:'Diver Down',type:'Yakın menzilli Stand',description:'Nesnelerin ve canlıların içine dalıp yapısını içeriden değiştirebilir; depoladığı darbeyi farklı bir noktada açığa çıkarabilir.',facts:{'Yetenek':'Yapılara girme ve içlerini yeniden düzenleme','Kullanıcı':'Narciso Anasui'}},events:['Jolyne’yle hapishanede ittifak kurar.','Pucci’nin planını durdurmak için onunla birlikte savaşır.','Jolyne’yi korurken son çatışmada hayatını kaybeder.'],image:null,source:'Manga/anime: Stone Ocean (Part 6).'},
 {id:'emporio-alnino',name:'Emporio Alnino',part:6,role:'Jolyne’nin müttefiki · Stone Ocean',intro:'Hapishane içinde saklanan, Pucci’nin planı ve hayalet odaları hakkında bilgi sahibi çocuk.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Dikkatli, zeki ve cesur',ability:'Stand kullanıcısı',stand:{name:'Burning Down the House',type:'Hayalet oda Stand’i',description:'Artık var olmayan nesnelerin hayalet biçimlerine ve hapishanedeki gizli hayalet odaya erişmesini sağlar.',facts:{'Yetenek':'Hayalet oda ve nesnelere erişim','Kullanıcı':'Emporio Alnino'}},events:['Jolyne’ye hapishanede yol gösterir ve müttefiklerini tanıtır.','Weather Report’un Stand diskini alarak Pucci’ye karşı kullanır.','Evrenin değişiminin ardından hayatta kalan tek eski ekip üyesi olur.'],image:null,source:'Manga/anime: Stone Ocean (Part 6).'}
);

window.JOJO_CHARACTERS.push(
 {id:'muhammad-avdol',name:'Muhammad Avdol',part:3,role:'Joestar müttefiki · Stardust Crusaders',intro:'Joseph’in dostu ve Stand kullanıcısı Avdol, Jotaro’nun Mısır yolculuğuna katılır.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Bilge, temkinli ve sadık',ability:'Stand kullanıcısı',stand:{name:'Magician’s Red',type:'Alev temelli Stand',description:'Ateşi üretip kontrol edebilir; alevleri şekillendirerek saldırı ve algılama amacıyla kullanır.',facts:{'Yetenek':'Ateş üretme ve kontrol etme','Kullanıcı':'Muhammad Avdol'}},events:['Jotaro’nun Stand gücünü tanımasına yardım eder.','Mısır’a giden ekipte yer alır ve düşman Stand kullanıcılarıyla savaşır.','Vanilla Ice’la çatışmasında hayatını kaybeder.'],image:null,source:'Manga/anime: Stardust Crusaders (Part 3).'},
 {id:'noriaki-kakyoin',name:'Noriaki Kakyoin',part:3,role:'Joestar müttefiki · Stardust Crusaders',intro:'DIO’nun kontrolünden kurtarılan Japon öğrenci; Jotaro’nun ekibine katılır.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Zeki, sakin ve güvenilir',ability:'Stand kullanıcısı',stand:{name:'Hierophant Green',type:'Uzak menzilli Stand',description:'Esnek ve uzun menzilli biçimiyle uzaktan saldırabilir; Emerald Splash adlı saldırısını kullanır.',facts:{'Yetenek':'Uzak menzilli saldırılar ve Emerald Splash','Kullanıcı':'Noriaki Kakyoin'}},events:['DIO’nun etkisi altındayken Jotaro’yla karşılaşır ve kurtarılır.','Mısır yolculuğunda ekibe katılır.','The World’ün zaman durdurma gücünü ortaya çıkaran mücadelede hayatını kaybeder.'],image:null,source:'Manga/anime: Stardust Crusaders (Part 3).'},
 {id:'jean-pierre-polnareff',name:'Jean Pierre Polnareff',part:3,role:'Joestar müttefiki · Stardust Crusaders',intro:'Kız kardeşinin intikamını arayan Fransız kılıç ustası; DIO’ya karşı verilen yolculukta Jotaro’yla birleşir.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Açık sözlü, cesur ve dostlarına bağlı',ability:'Stand kullanıcısı',stand:{name:'Silver Chariot',type:'Kılıç kullanan yakın menzilli Stand',description:'Rapier kullanan, çok hızlı bir Stand’dir; zırhını çıkararak hızını artırabilir.',facts:{'Yetenek':'Yüksek hızlı kılıç dövüşü','Kullanıcı':'Jean Pierre Polnareff'}},events:['DIO’nun hizmetindeki J. Geil’i bulmak için ekiple iş birliği yapar.','DIO’nun Mısır’daki karargâhına ulaşan ekibin parçası olur.','DIO yenildikten yıllar sonra Passione’ye karşı Giorno’nun müttefiki olur.'],image:null,source:'Manga/anime: Stardust Crusaders ve Golden Wind.'},
 {id:'iggy',name:'Iggy',part:3,role:'Joestar müttefiki · Stardust Crusaders',intro:'New York’tan Mısır’a getirilen, bağımsız karakterli Boston terrier ve Stand kullanıcısı.',birth:'Bilinmiyor',height:'Kaynaklarda belirtilmemiş',personality:'Bağımsız, inatçı ve zamanla fedakâr',ability:'Stand kullanıcısı',stand:{name:'The Fool',type:'Kum temelli Stand',description:'Kumu kullanarak zırh, kanat ve farklı biçimler oluşturabilir.',facts:{'Yetenek':'Kumu farklı biçimlerde şekillendirme','Kullanıcı':'Iggy'}},events:['Başlangıçta ekiple iş birliği yapmak istemez.','Mısır’daki düşmanlara karşı ekibe yardım eder.','Vanilla Ice’la karşılaşmasında Polnareff’i kurtarmak için kendini feda eder.'],image:null,source:'Manga/anime: Stardust Crusaders (Part 3).'},
 {id:'holly-kujo',name:'Holly Kujo',part:3,role:'Jotaro’nun annesi · Stardust Crusaders',intro:'Jotaro’nun annesi; DIO’nun geri dönüşüyle tetiklenen Stand gücü sağlığını tehdit eder.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Şefkatli, iyimser ve ailesine düşkün',ability:'Uyanan Stand gücünü kontrol edemez',stand:null,events:['Jotaro’nun annesidir ve Joseph’in kızıdır.','Stand gücü, bedeninin dayanamayacağı şekilde ortaya çıkar.','Jotaro ve Joseph’in Mısır’a gidip DIO’yu durdurması için zaman sınırı oluşturur.'],image:null,source:'Manga/anime: Stardust Crusaders (Part 3).'},
 {id:'koichi-hirose',name:'Koichi Hirose',part:4,role:'Josuke’nin dostu · Diamond is Unbreakable',intro:'Morioh’da yaşayan öğrenci; Josuke’yle tanıştıktan sonra Stand savaşlarına dahil olur.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Dürüst, cesur ve sorumluluk sahibi',ability:'Stand kullanıcısı',stand:{name:'Echoes',type:'Gelişen Stand',description:'Ses efektlerini ve sözcükleri hedeflere uygulayabilir; farklı Act biçimleri farklı yetenekler sergiler.',facts:{'Yetenek':'Ses ve sözcükleri hedefe uygulama; Act’lere göre değişir','Kullanıcı':'Koichi Hirose'}},events:['Josuke’yle arkadaş olur ve Morioh’daki Stand kullanıcılarıyla karşılaşır.','Echoes, çatışmalar boyunca yeni Act biçimlerine evrilir.','Yoshikage Kira’nın kimliğini açığa çıkarmaya yardım eder.'],image:null,source:'Manga/anime: Diamond is Unbreakable (Part 4).'},
 {id:'okuyasu-nijimura',name:'Okuyasu Nijimura',part:4,role:'Josuke’nin dostu · Diamond is Unbreakable',intro:'Morioh’da Josuke’yle karşılaşan Stand kullanıcısı; kardeşinin ölümünden sonra onunla arkadaş olur.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Dobra, sadık ve iyi kalpli',ability:'Stand kullanıcısı',stand:{name:'The Hand',type:'Yakın menzilli güç Stand’i',description:'Sağ eliyle sildiği alanı ortadan kaldırır; silinen boşlukta kalan nesneler birbirine yaklaşır.',facts:{'Yetenek':'Sağ elle uzay ve nesneleri silme','Kullanıcı':'Okuyasu Nijimura'}},events:['Josuke’yle başlangıçta düşman olarak karşılaşır.','Josuke’nin kardeşi Keicho’yla çatışması sonrasında onun yanında yer alır.','Morioh’yu Kira’dan korumaya yardım eder.'],image:null,source:'Manga/anime: Diamond is Unbreakable (Part 4).'},
 {id:'rohan-kishibe',name:'Rohan Kishibe',part:4,role:'Manga sanatçısı · Diamond is Unbreakable',intro:'Morioh’da yaşayan manga sanatçısı; insanları gözlemleme merakı Stand gücüyle birleşir.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Meraklı, kendine güvenen ve takıntılı biçimde gözlemci',ability:'Stand kullanıcısı',stand:{name:'Heaven’s Door',type:'Bilgi ve kontrol Stand’i',description:'Hedefleri bir kitaba dönüştürerek anılarını okuyabilir ve sayfalarına talimatlar yazabilir.',facts:{'Yetenek':'Hedefin anılarını okuma ve talimat yazma','Kullanıcı':'Rohan Kishibe'}},events:['Josuke ve Koichi’yle karşılaşır.','Heaven’s Door’u kullanarak çevresindeki insanları ve olayları araştırır.','Morioh’daki Kira soruşturmasına katkıda bulunur.'],image:null,source:'Manga/anime: Diamond is Unbreakable (Part 4).'},
 {id:'yukako-yamagishi',name:'Yukako Yamagishi',part:4,role:'Koichi’nin müttefiki · Diamond is Unbreakable',intro:'Koichi’ye yoğun biçimde ilgi duyan Morioh’lu öğrenci; Stand’i saçlarını kontrol etmesini sağlar.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Tutkulu, kararlı ve zamanla daha anlayışlı',ability:'Stand kullanıcısı',stand:{name:'Love Deluxe',type:'Vücut temelli Stand',description:'Yukako kendi saçlarını olağanüstü uzunlukta uzatıp kontrol edebilir.',facts:{'Yetenek':'Saçları uzatma ve kontrol etme','Kullanıcı':'Yukako Yamagishi'}},events:['Koichi’ye duyduğu ilgiyle onu takip etmeye başlar.','Koichi’yle yaşadığı olaylar sonrasında davranışını değiştirmeye çalışır.','Morioh’daki tehlikeler sırasında Koichi’nin yanında yer alır.'],image:null,source:'Manga/anime: Diamond is Unbreakable (Part 4).'},
 {id:'reimi-sugimoto',name:'Reimi Sugimoto',part:4,role:'Morioh’nun hayaleti · Diamond is Unbreakable',intro:'On beş yıl önce Kira’nın kurbanı olan genç kız; hayalet sokağından yaşayanlara seslenir.',birth:'Kaynaklarda belirtilmemiş',height:'Kaynaklarda belirtilmemiş',personality:'Nazik, kararlı ve yardımsever',ability:'Hayalet olarak varlığını sürdürür',stand:null,events:['Rohan’a çocukluğunda yaşanan cinayeti hatırlatır.','Josuke ve arkadaşlarından Morioh’daki seri katili bulmalarını ister.','Kira yenilince hayalet sokağındaki ruhlarla birlikte huzura kavuşur.'],image:null,source:'Manga/anime: Diamond is Unbreakable (Part 4).'}
);


/* Additional canon context for profile and Stand dossier panels. */
window.JOJO_CHARACTER_DETAILS = {
 'jonathan-joestar':'Joestar malikânesinin varisi olarak yetişen Jonathan’ın hayatı, Dio’nun aileye katılmasıyla değişir. Taş Maske’nin ortaya çıkması, aralarındaki rekabeti Hamon ve vampir güçlerinin karşı karşıya geldiği bir mücadeleye dönüştürür. Jonathan, Dio’yu durdurmaya çalışırken merhametini ve onurunu korur.',
 'dio-brando':'Dio, evlatlık olarak Joestar ailesine katılır ve ailenin servetini ele geçirmeyi amaçlar. Taş Maske onu vampire dönüştürür; Jonathan’la başlayan düşmanlık sonraki Joestar kuşaklarına da uzanır.',
 'joseph-joestar':'Joseph, Jonathan’dan devraldığı aile mücadelesinde New York’tan Avrupa ve Orta Doğu’ya uzanan bir yolculuğa çıkar. Hamon’u doğaçlama ve ekip çalışmasıyla birleştirerek Sütun Adamları’na karşı savaşır. Yıllar sonra Stardust Crusaders’da daha yaşlı bir müttefik olarak yeniden karşımıza çıkar.',
 'jotaro-kujo':'Jotaro’nun ilk yolculuğu annesi Holly’yi kurtarmak için zamana karşı verilen bir mücadeledir; ekip Japonya’dan Mısır’a gider. Jotaro daha sonra Morioh’ya dönerek araştırma ve rehberlik rolü üstlenir, ardından Jolyne’nin Pucci’ye karşı mücadelesine katılır.',
 'josuke-higashikata':'Jotaro’nun Morioh’ya gelişi ve Joestar ailesiyle bağı açıklaması Josuke’nin hikâyesini başlatır. Josuke, sınıf arkadaşları ve diğer Stand kullanıcılarıyla kasabasını korurken Morioh’da yaşayan seri katilin izini sürer.',
 'giorno-giovanna':'Giorno, Passione içinde yükselip örgütü içeriden değiştirme hedefiyle yola çıkar. Kararlılığı onu Bucciarati’nin ekibiyle birlikte gizemli Patron’a karşı bir çatışmanın içine çeker. Gold Experience hem savaşta hem de yaralıları kurtarmakta kullanılır.',
 'jolyne-cujoh':'Jolyne’nin hapse girmesi, babasının anılarını ve Pucci’nin planını içeren daha büyük bir mücadelenin başlangıcı olur. Hapisten kaçmaya çalışan genç bir kadından, evrenin geleceğini koruyan ekibin merkezindeki savaşçıya dönüşür.',
 'johnny-joestar':'Yürüyemeyen eski jokey Johnny, Gyro’nun Spin’ini gördükten sonra Steel Ball Run yarışına katılır. İkilinin ortaklığı ve Kutsal Ceset’i arayışları yarışı güç, fedakârlık ve ülkenin geleceği üzerine bir mücadeleye dönüştürür.',
 'josuke-gappy':'Morioh’da hafızasını ve kimliğini bilmeden bulunan Josuke, Yasuho’dan ve Higashikata ailesinden yardım alarak geçmişini araştırır. Bu araştırma Duvar Gözleri’ni, Rokakaka meyvesini ve kasabadaki açıklanamayan felaketleri açığa çıkarır.',
 'jodio-joestar':'Jodio’nun açıkça dile getirdiği hedef çok zengin olmaktır. Kardeşi Dragona ve ekibiyle Hawaii’de yeraltı dünyasında çalışır; Lava Rock ve HOWLER şirketiyle ilgili görevleri devam eden Part 9 hikâyesinin merkezine taşır.',
 'diavolo':'Diavolo Passione’yi gölgelerin içinden yönetir ve gizliliği güvencesi olarak görür. Bucciarati’nin ekibi Trish’i ona teslim etmeyi reddedince onlara karşı harekete geçer. Giorno’nun zaferiyle Diavolo sonu gelmeyen ölümlere mahkûm olur.',
 'yoshikage-kira':'Kira, kadınların ellerine duyduğu takıntıyı Morioh’da sürdürdüğü sıradan yaşamın arkasına gizler. Yeni bir kimlikle izini kaybettirmeye çalışsa da Josuke ve dostları kasabadaki cinayetleri ona bağlayan ipuçlarının peşini bırakmaz.',
 'enrico-pucci':'DIO’yla kurduğu bağ, Pucci’nin insanlığın önceden belirlenmiş bir Cennet’e ulaşması gerektiğine inanmasına yol açar. Jotaro’nun anılarını ele geçirme planı Jolyne ve hapishanedeki diğer kişileri kader ve evrenin düzeni üzerine bir çatışmaya sürükler.',
 'funny-valentine':'Valentine, Kutsal Ceset’i aramak için Steel Ball Run yarışını kullanır. Ceset’in gücünü Amerika Birleşik Devletleri’nde toplamanın ülkesini koruyacağına inanır; bu amaç onu Johnny ve Gyro’yla karşı karşıya getirir.',
 'tooru':'Tooru’nun Yasuho’yla geçmişi, onu Higashikata ailesi ve Locacaca çevresindeki araştırmaya bağlar. Stand’i, onu takip etme girişimlerini felaket zincirine dönüştürür ve araştırmayı başlı başına tehlikeli hâle getirir.',
 'bruno-bucciarati':'Passione içinde güvenilen bir ekip lideri olan Bucciarati, Giorno’nun kararlılığını gördükten sonra onu ekibine alır. Trish’i teslim etme emri, onu örgüte itaat etmekle tehlikedeki birini korumak arasında seçim yapmaya zorlar.',
 'gyro-zeppeli':'Gyro, ailesi ve Napoli Krallığı’yla bağlantılı kişisel bir amaçla yarışa katılır. Johnny’ye Spin’i öğretmesi ortaklıklarının temelini oluşturur; Kutsal Ceset’in bulunması yarışın ardındaki daha büyük mücadeleyi ortaya çıkarır.',
 'rohan-kishibe':'Rohan, manga sanatçısı olarak doğrudan gözlemi işinin vazgeçilmez bir parçası sayar. Heaven’s Door insanları bir kitap gibi okumasına imkân verir; Rohan bu gücü Morioh’daki olayları ve gizemleri araştırmak için kullanır.'
};
window.JOJO_STAND_DETAILS = {
 'jotaro-kujo':{details:['Star Platinum yakın dövüşte olağanüstü hız, güç ve hassasiyet gösterir.','Keskin görüşü ve ince kontrolü, Jotaro’nun güçlü saldırıların yanı sıra hassas işler yapmasını da sağlar.','DIO’yla savaşırken Jotaro, Star Platinum’un zamanı durdurabildiğini keşfeder.'],limits:['Yakın menzilli bir Stand olduğu için Jotaro’nun çoğu zaman hedefe yaklaşması gerekir.','Zamanı durdurma süresi kısadır; DIO’yla çatışma boyunca gelişir.']},
 'joseph-joestar':{details:['Hermit Purple, Joseph’in uzatıp kontrol edebildiği dikenli sarmaşıklar biçiminde görünür.','Joseph Hamon’u sarmaşıklardan geçirerek Ripple enerjisini iletebilir.','Bir kamera veya başka bir araç kullanarak hedef hakkında bilgi veren spiritüel fotoğraflar elde edebilir.'],limits:['Spiritüel fotoğraf tekniği görüntüyü almak için kullanılan kameraya veya araca zarar verebilir.','Hermit Purple daha çok bilgi toplama, bağlama ve uzaktan destek için kullanılır.']},
 'josuke-higashikata':{details:['Crazy Diamond hasarlı nesne ve canlıları önceki bir hâle döndürerek onarabilir.','Josuke bu gücü yaratıcı biçimde kullanır: parçaları bir araya getirebilir veya onarılan malzemeyi başka yöne yönlendirebilir.'],limits:['Crazy Diamond Josuke’nin kendisini iyileştiremez.','Ölmüş birini hayata döndüremez.']},
 'giorno-giovanna':{details:['Gold Experience cansız nesnelere yaşam vererek onları canlı organizmalara dönüştürebilir.','Giorno yarattığı canlıları şaşırtma, iz sürme, savunma ve destek amacıyla kullanır.','Stand’in verdiği yaşam enerjisi, vurduğu kişinin duyularını aşırı biçimde etkileyebilir.'],limits:['Yaratılan canlılar zarar görebilir; bu yetenek onları dokunulmaz yapmaz.']},
 'jolyne-cujoh':{details:['Stone Free, Jolyne’nin bedeninin bazı kısımlarını kontrol edebildiği ipliklere ayırmasını sağlar.','Jolyne iplikleri ağ, tuzak ve bariyer hâline getirebilir; titreşimleri kullanarak sesleri algılayabilir.','İplikleri bir araya getirerek yakın dövüşte kullandığı insansı Stand biçimini oluşturabilir.'],limits:['Bedeninin fazla kısmını ipliğe ayırmak, onu koruyacak daha az madde bırakır.','İpliklerin erişimi sınırlıdır; iplikler zarar görebilir veya kopabilir.']}
};

Object.assign(window.JOJO_STAND_DETAILS, {
 'dio-part3':{details:['The World yakın dövüşe ve üstün fiziksel güce odaklanan insansı bir Stand’dir.','En belirgin yeteneği, DIO’nun zaman durmuşken hareket edebilmesini sağlamasıdır.','DIO bu gücü Jotaro’yla yaptığı son savaş boyunca geliştirir.'],limits:['Zamanı durdurma gücüne kıyasla Stand’in erişim menzili kısadır.','Zamanın durduğu süre sınırlıdır ve hikâye boyunca değişir.']},
 'mohammed-avdol':{details:['Magician’s Red saldırı ve savunmada kullanmak üzere ateş üretir ve kontrol eder.','Avdol alevlerine biçim verebilir; Crossfire Hurricane saldırısı bunun örneklerindendir.','Stand yakındaki canlı hedefleri ısı aracılığıyla algılayabilir.']},
 'noriaki-kakyoin':{details:['Hierophant Green uzayıp esnek bir biçim alabilir ve uzaktan saldırabilir.','Kakyoin hareketleri algılamak için sarmaşıklarını bir alana yayabilir.','Emerald Splash, Stand’in imza niteliğindeki menzilli saldırısıdır.']},
 'jean-pierre-polnareff':{details:['Silver Chariot rapier kullanan, hızlı ve hassas kılıç dövüşünde uzman bir Stand’dir.','Zırhını çıkarmak, korumasını azaltırken hızını artırır.','Polnareff çıkardığı zırhı görsel bir şaşırtmaca olarak kullanabilir.']},
 'iggy':{details:['The Fool kumu kontrol ederek zırh, kanat ve inandırıcı biçimler oluşturabilir.','Bedenini kum biçiminden daha katı bir görünüme dönüştürebilir.','Iggy Stand’i havada hareket etmek ve çatışmalarda korunmak için kullanır.']},
 'yoshikage-kira':{details:['Killer Queen’in eliyle dokunduğu nesneler bombaya dönüşebilir.','Sheer Heart Attack ısıyı takip eden otomatik bir bombadır.','Bites the Dust, Kira’nın hikâyenin ilerleyen bölümünde geliştirdiği ayrı bir yetenektir.'],limits:['Kira’nın temel bomba yeteneği, bombaya çevirmek istediği nesneye dokunmasını gerektirir.']},
 'koichi-hirose':{details:['Echoes, her biri farklı biçim ve yeteneğe sahip Act aşamalarıyla gelişir.','Act 1 sesleri yüzeylere yerleştirir; Act 2 yazılı ses efektlerini karşılık gelen etkilere dönüştürür.','Act 3, “3 Freeze” yeteneğiyle hedefin üzerine ağır bir yük bindirebilir.']},
 'okuyasu-nijimura':{details:['The Hand, sağ elinin geçtiği uzayı siler.','Uzay silindiğinde iki tarafta kalan nesneler birbirine yaklaşır.','Okuyasu’nun doğrudan dövüş tarzı, Stand’in uzayı silme gücünü özellikle tehlikeli kılar.']},
 'rohan-kishibe':{details:['Heaven’s Door bir kişiyi Rohan’ın okuyabileceği sayfalara dönüştürür.','Bu sayfalara talimatlar yazarak kişinin yapabileceklerini veya hatırladıklarını etkileyebilir.','Rohan yeteneğiyle karşılaştığı kişilerden doğrudan bilgi edinir.']},
 'guido-mista':{details:['Sex Pistols, Mista’nın mermilerine binip onları yönlendiren küçük ve bağımsız Stand birimlerinden oluşur.','Mermi ateşlendikten sonra ona vurarak gidiş yönünü değiştirebilirler.','Birimler Mista’yla iletişim kurar ve revolverini doldurmasına yardım edebilir.']},
 'narancia-girga':{details:['Aerosmith, silahlar ve bombalar taşıyan küçük bir uçaktır.','Radarı karbondioksiti algılayarak Narancia’nın nefes alan hedefleri bulmasını sağlar.','Bu radar doğrudan görüşün dışındaki hedefleri de açığa çıkarabilir.']},
 'leone-abbacchio':{details:['Moody Blues geçmişte yaşanan olayları, o sıradaki kişilerin görünüş ve hareketleriyle yeniden canlandırır.','Abbacchio yeniden oynatılan sahnenin içinde ilerleyerek yaşananları inceleyebilir.','Stand doğrudan dövüşten çok araştırma ve iz sürmede kullanılır.']},
 'trish-una':{details:['Spice Girl dokunduğu nesneleri yumuşatıp esnetebilir.','Yumuşayan yüzeyler darbeleri emer ve kırılmadan bükülebilir.','Trish bu yetenekle sert çevre unsurlarını esnek hâle getirir.']},
 'ermes-costello':{details:['Kiss çıkartmaları yapıştırıldıkları nesne veya vücut parçasının bir kopyasını oluşturur.','Çıkartma kaldırıldığında kopyalar birleşir ve güçlü bir çarpışma yaratır.','Ermes çıkartmaları kendisine veya başka hedeflere yapıştırabilir.']},
 'weather-report':{details:['Weather Report çevresindeki atmosfer koşullarını kontrol eder.','Hava gücü hem belirli bir noktada hem de daha geniş ölçekte kullanılabilir.','Heavy Weather, Weather Report’un geri kazandığı anılarla bağlantılı ayrı bir yetenektir.']},
 'narciso-anasui':{details:['Diver Down bir nesnenin veya kişinin içine girip iç yapısını yeniden düzenleyebilir.','Anasui bir darbeyi hedefin içinde depolayıp daha sonra açığa çıkarabilir.','Stand, dış yüzeyi parçalamadan yapının içini değiştirebilir.']},
 'emporio-alnino':{details:['Burning Down the House, Emporio’ya hapishanedeki gizli hayalet odaya erişim sağlar.','Artık var olmayan nesnelerin hayalet kopyalarıyla etkileşebilir.','Stand’in işlevi Emporio’nun büyüdüğü yerle doğrudan bağlantılıdır.']},
 'funny-valentine':{details:['D4C, Valentine’ın iki yüzey arasından geçerek paralel dünyalara gitmesini sağlar.','Başka dünyalardaki kişi veya nesneleri kendi dünyasına getirebilir.','Valentine Kutsal Ceset’i elde ettikten sonra Love Train yeteneğini kazanır.']},
 'diego-brando':{details:['Scary Monsters Diego’yu ve diğer canlıları dinozorlara dönüştürebilir.','Dönüşen canlılar dinozor özellikleri ve gelişmiş fiziksel yetenekler kazanır.','Diego dönüşümü temas yoluyla yayabilir.']},
 'hot-pants':{details:['Cream Starter et benzeri bir madde püskürten sprey biçimli bir Stand’dir.','Hot Pants bunu görünüş değiştirmek ve yaraları tedavi etmek için kullanabilir.','Stand yakın mesafeli saldırılarda da kullanılabilir.']},
 'ringo-roadagain':{details:['Mandom zamanı altı saniye geriye sarabilir.','Ringo gücü bileğindeki saati çevirerek etkinleştirir.','Az önce yaşananları bilerek kısa bir karşılaşmayı yeniden oynamasına imkân verir.'],limits:['Zamanı yalnızca altı saniyelik bir aralığa geri sarabilir.']},
 'jodio-joestar':{details:['November Rain, Jodio’nun çevresindeki sınırlı bir alana yağmur yağdırır.','Yağmur damlaları çarptıkları şeylerin üzerine çok büyük bir baskı uygular.','Jodio yağışın alanını ve düzenini kontrol edebilir.']},
 'dragona-joestar':{details:['Smooth Operators yüzeylerde hareket eden birkaç küçük birimden oluşur.','Bu birimler görünüş özelliklerini ve nesneleri bir konumdan diğerine kaydırabilir.','Dragona gücü hassas değişikliklerde ve çatışmalarda kullanır.']},
 'paco-lovelantes':{details:['The Hustle, Paco’nun kaslarını olağanüstü hassasiyetle kontrol edip germesini sağlar.','Kas dokusuyla yüzeylere tutunabilir ve nesneleri bedenine sabitleyebilir.','Bu özellik bedenini hem gizlenme hem de yakın dövüş için kullanmasına yardım eder.']},
 'usagi-alohaoe':{details:['The Matte Kudasai başka bir kişinin istediği nesneye dönüşebilir.','İsteği Usagi’den başka birinin dile getirmesi gerekir.','Stand’in dönüşeceği şeyi bu istek belirler.'],limits:['Usagi nesneyi tek başına seçemez; başka biri isteğini ifade etmelidir.']},
 'yasuho-hirose':{details:['Paisley Park bilgi ve elektronik sistemlerde arama yapabilir.','Bulduğu bilgilere göre Yasuho’ya yararlı yollar veya seçenekler gösterebilir.','Cihazlara veya verilere erişebildiğinde destek işlevi güçlenir.']},
 'rai-mamezuku':{details:['Doggy Style, Rai’nin bedenini kontrol edebildiği ipliklere ayırmasını sağlar.','Bu iplikleri uzatıp hareket veya saldırı için yönlendirebilir.','Bedeninin bazı kısımlarını dar alanlardan geçirebilir.']},
 'jobin-higashikata':{details:['Speed King dokunduğu hedefte ısı depolar ve bu ısıyı daha sonra açığa çıkarır.','Jobin depolanan ısıyla belirli noktalarda ani sıcaklık değişimleri yaratabilir.','Gücün işlemesi için hedefin önce ısıtılması gerekir.']},
 'tooru':{details:['Wonder of U, Başhekim görünümünde ortaya çıkar ve Tooru’yu felaket akışıyla korur.','Onu takip eden veya yaklaşmaya çalışan kişiler giderek ağırlaşan kazalarla karşılaşır.','Takip eden kişi zarar vermeyi amaçlamasa bile takip eylemi tehlikelidir.'],limits:['Felaket, Stand’i veya kullanıcısını takip etme girişimine bağlıdır; hikâyede bu akışa karşı koymanın yolları da gösterilir.']}
});
